package com.ae22mp.parcial2pdm.local

import com.ae22mp.parcial2pdm.model.Product

val localProducts = listOf(
Product(1, "Bluetooth Headphones", "Electronics", "$29.99", "Wireless headphones with noise cancellation.", "https://example.com/img1.jpg", false),
Product(2, "RGB Mechanical Keyboard", "Electronics", "$59.99", "Backlit mechanical keyboard with red switches.", "https://example.com/img2.jpg", false),
Product(3, "Anti-Theft Backpack", "Accessories", "$34.50", "Water-resistant backpack with hidden zippers.", "https://example.com/img3.jpg", false),
Product(4, "Smartwatch", "Electronics", "$79.99", "Health tracking and real-time notifications.", "https://example.com/img4.jpg", false),
Product(5, "Men's Casual Shirt", "Clothing", "$19.90", "Cotton shirt for daily wear.", "https://example.com/img5.jpg", false),
Product(6, "Women's Running Shoes", "Footwear", "$45.00", "Comfortable sneakers for running or walking.", "https://example.com/img6.jpg", false),
Product(7, "Ergonomic Office Chair", "Home", "$129.99", "Ergonomic design with lumbar support.", "https://example.com/img7.jpg", false),
Product(8, "LED Desk Lamp", "Home", "$22.99", "Adjustable light with USB charging port.", "https://example.com/img8.jpg", false),
Product(9, "Wireless Mouse", "Electronics", "$14.99", "Ergonomic and quiet wireless mouse.", "https://example.com/img9.jpg", false),
Product(10, "Portable Charger 10000mAh", "Electronics", "$25.00", "External battery with dual USB ports.", "https://example.com/img10.jpg", false),
Product(11, "Oversized Hoodie", "Clothing", "$29.00", "Comfortable hoodie for cold days.", "https://example.com/img11.jpg", false),
Product(12, "Classic Sunglasses", "Accessories", "$17.50", "UV400 protection with timeless design.", "https://example.com/img12.jpg", false),
Product(13, "Memory Foam Pillow", "Home", "$39.99", "Contours to your head and neck.", "https://example.com/img13.jpg", false),
Product(14, "Thermal Bottle 500ml", "Accessories", "$15.99", "Keeps drinks hot or cold for hours.", "https://example.com/img14.jpg", false),
Product(15, "Portable Blender", "Appliances", "$32.00", "Perfect for quick smoothies and juices.", "https://example.com/img15.jpg", false),
Product(16, "Electric Toothbrush", "Personal Care", "$24.99", "Deep cleaning with smart timer.", "https://example.com/img16.jpg", false),
Product(17, "Makeup Brush Set", "Beauty", "$18.50", "Includes 10 professional brushes.", "https://example.com/img17.jpg", false),
Product(18, "Winter Slippers", "Footwear", "$20.00", "Cozy lining for maximum comfort.", "https://example.com/img18.jpg", false),
Product(19, "Queen Bed Sheet Set", "Home", "$49.90", "Soft microfiber sheet set.", "https://example.com/img19.jpg", false),
Product(20, "Full HD Webcam", "Electronics", "$35.99", "Ideal for video calls and streaming.", "https://example.com/img20.jpg", false),
Product(21, "Multifunction Printer", "Electronics", "$99.00", "Print, scan, and copy in high quality.", "https://example.com/img21.jpg", false),
Product(22, "Steam Iron", "Appliances", "$38.99", "Smooth glide and fast heating.", "https://example.com/img22.jpg", false),
Product(23, "24-inch Monitor", "Electronics", "$129.00", "Full HD screen with thin bezels.", "https://example.com/img23.jpg", false),
Product(24, "Folding Table", "Home", "$49.00", "Perfect for small spaces or picnics.", "https://example.com/img24.jpg", false),
Product(25, "Leather Belt", "Accessories", "$19.99", "Adjustable, classic, and elegant.", "https://example.com/img25.jpg", false),
Product(26, "Touchscreen Winter Gloves", "Clothing", "$13.99", "Compatible with smartphones.", "https://example.com/img26.jpg", false),
Product(27, "Kitchen Knife Set", "Home", "$27.90", "5 knives with magnetic holder.", "https://example.com/img27.jpg", false),
Product(28, "Air Fryer", "Appliances", "$89.99", "Healthy cooking with no oil.", "https://example.com/img28.jpg", false),
Product(29, "4K Action Camera", "Electronics", "$59.99", "Waterproof up to 30 meters.", "https://example.com/img29.jpg", false),
Product(30, "1TB External Hard Drive", "Electronics", "$69.00", "Portable storage solution.", "https://example.com/img30.jpg", false),
Product(31, "Compact Umbrella", "Accessories", "$12.99", "Automatic and wind-resistant.", "https://example.com/img31.jpg", false),
Product(32, "Floral Perfume 100ml", "Beauty", "$45.00", "Fresh and long-lasting fragrance.", "https://example.com/img32.jpg", false),
Product(33, "Women's Summer Sandals", "Footwear", "$23.50", "Trendy and comfortable design.", "https://example.com/img33.jpg", false),
Product(34, "Sports Cap", "Clothing", "$9.99", "Lightweight and breathable.", "https://example.com/img34.jpg", false),
Product(35, "A5 Notebook 100 pages", "Stationery", "$5.50", "Thick, high-quality paper.", "https://example.com/img35.jpg", false),
Product(36, "Desk Organizer", "Home", "$14.90", "Keeps your workspace tidy.", "https://example.com/img36.jpg", false),
Product(37, "Screen Cleaning Kit", "Accessories", "$10.00", "Ideal for phones, tablets, and laptops.", "https://example.com/img37.jpg", false),
Product(38, "Watercolor Art Set", "Stationery", "$25.99", "Brushes, paints, and paper included.", "https://example.com/img38.jpg", false),
Product(39, "Car Phone Mount", "Electronics", "$11.90", "Universal compatibility and easy setup.", "https://example.com/img39.jpg", false),
Product(40, "Classic Card Games Set", "Toys", "$8.00", "Fun for the whole family.", "https://example.com/img40.jpg", false),
Product(41, "Thermal Coffee Mug", "Home", "$16.99", "Keeps beverages warm for hours.", "https://example.com/img41.jpg", false),
Product(42, "15.6'' Laptop Sleeve", "Accessories", "$18.50", "Waterproof and padded design.", "https://example.com/img42.jpg", false),
Product(43, "Anti-Stress Ball", "Health", "$4.99", "Great for hand and mind relaxation.", "https://example.com/img43.jpg", false),
Product(44, "Charcoal Facial Soap", "Personal Care", "$7.99", "Deep cleansing for oily skin.", "https://example.com/img44.jpg", false),
Product(45, "First Aid Kit", "Health", "$22.50", "Essential items for emergencies.", "https://example.com/img45.jpg", false),
Product(46, "WiFi Security Camera", "Electronics", "$42.00", "Remote monitoring via smartphone.", "https://example.com/img46.jpg", false),
Product(47, "Mini USB Fan", "Electronics", "$9.99", "Compact and silent cooling.", "https://example.com/img47.jpg", false),
Product(48, "Basic Tool Set", "Home", "$30.00", "Includes hammer, screwdrivers, and more.", "https://example.com/img48.jpg", false),
Product(49, "Multipurpose Scissors", "Stationery", "$3.99", "Sharp and safe cutting.", "https://example.com/img49.jpg", false),
Product(50, "Microfiber Travel Towel", "Home", "$12.50", "Quick-drying and compact.", "https://example.com/img50.jpg", false)
)